apps/exam/urls.py
from django.conf.urls import url
from . import views
# from django.contrib import admin

urlpatterns = [
    url(r'^dashboard/$', views.dashboard, name = 'dashboard'),
    url(r'^item/(?P<id>\d+)$', views.item, name = 'item'),
    url(r'^item/create_form$', views.new_item, name = 'new_item'),
    url(r'^item/create$', views.create, name = 'create'),
    url(r'^logout/$', views.logout, name = 'logout'),
    url(r'^delete/(?P<id>\d+)$', views.delete, name = 'delete'),
    url(r'^remove/(?P<id>\d+)$', views.remove, name = 'remove'),
    url(r'^add/(?P<id>\d+)$', views.add, name = 'add'),
]

beltExam/urls.py
from django.conf.urls import url, include
# from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.login.urls', namespace = 'login')),
    url(r'^exam/', include('apps.exam.urls', namespace = 'exam')),
]

apps/exam/models.py
from __future__ import unicode_literals
from ..login.models import User
from django.db import models

# Create your models here.
class itemManager(models.Manager):
    #creates a new item with a many t omany relationship with the user who creates it
    def create_item(self, postData, user_id):
        errors = []
        response = {}
        if self.filter(name = postData['item']):
            errors.append('**This item has already been added!**')
        if not len(postData['item']) >= 3:
            errors.append('**Item must contain at least 3 characters**')
        if errors:
            response['status'] = False
            response['errors'] = errors
        else:
            response['status'] = True
            user = User.objects.get(id = user_id)
            item = Item.objects.create(name = postData['item'], added_by_name = user.first_name, added_by_id = user_id)
            item.user.add(user)
        return response

    #deletes item from the database
    def delete(self, id):
        Item.objects.get(id=id).delete()
        return ##is this dumb?

    #adds item from wishlist to user's wishlist by estalishing many to many relaitonship
    def add(self, item_id, user_id):
        user = User.objects.get(id = user_id)
        item = Item.objects.get(id= item_id)
        item.user.add(user)
        return

    #remove item from user's wishlist by removing many to many relationship
    def remove(self, item_id, user_id):
        user = User.objects.get(id = user_id)
        item = Item.objects.get(id= item_id)
        item.user.remove(user)
        return

class Item(models.Model):
    name = models.CharField(max_length = 255)
    added_by_name = models.CharField(max_length = 255)
    added_by_id = models.IntegerField()
    user = models.ManyToManyField(User, related_name = "wish_items")
    created_at = models.DateTimeField(auto_now_add = True)
    apdated_at = models.DateTimeField(auto_now = True)
    objects = itemManager()

apps/exam/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.contrib import messages
from ..login.models import User
from .models import Item

#render's dashboard
def dashboard(request):
    if request.session['id']:
        context ={
            'user': User.objects.get(id = request.session['id']),
            'user_items': Item.objects.filter(user__id=request.session['id']),
            'other_items': Item.objects.exclude(user__id=request.session['id'])
        }
    return render(request, 'exam/dashboard.html', context)

#render's item page
def item(request, id):
    context={
        'item':Item.objects.get(id=id),
        'users': User.objects.filter(wish_items=id)
    }
    return render(request, 'exam/item.html', context)

#render's form for new item
def new_item(request):
    return render(request, 'exam/create_item.html')

#adds new item to db and redirects user to dashbaord
def create(request):
     response = Item.objects.create_item(request.POST, request.session['id'])
     if not response['status']:
            for error in response['errors']:
                messages.error(request, error)
            return redirect('exam:new_item')
     return redirect('exam:dashboard')

#deletes item from db
def delete(request,id):
    Item.objects.delete(id)
    return redirect('exam:dashboard')

#removes a  many to many relationship between a user and an item
def remove(request, id):
    Item.objects.remove(id, request.session['id'])
    return redirect('exam:dashboard')

#creates a many to many relationship between a user and an item
def add(request, id):
    Item.objects.add(id, request.session['id'])
    # user = User.objects.get(id = request.session['id'])
    # item = Item.objects.get(id=id)
    # item.user.add(user)
    return redirect('exam:dashboard')

#logs user out by clearing session and redirecting to login page
def logout(request):
    request.session.clear()
    return redirect('login:index')

apps/exam/templates/exam/create_item.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        {% load staticfiles %}
        <link rel="stylesheet" href="{% static 'exam/css/style.css' %}">
        <title>New Item</title>
    </head>
    <body>
        <div class="header">
            <h3 class="inline">Create a new wish for an item you'll never get</h3>
            <a href="{% url 'exam:dashboard' %}" class="inline">Dashboard</a>
            <a href="{% url 'exam:logout' %}" class="inline">Logout</a>
        </div>
        <form action="{% url 'exam:create' %}" method="post">
            {% csrf_token %}
            {% if messages %}
                {% for message in messages %}
                    <p class="red">{{ message }}</p>
                {% endfor %}
            {% endif %}
            <label for="">Item/Product: </label><input type="text" name="item">
            <input type="submit">
        </form>
    </body>
</html>

apps/exam/templates/exam/dashboard.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        {% load staticfiles %}
        <link rel="stylesheet" href="{% static 'exam/css/style.css' %}">
        <title>Dashboard</title>
    </head>
    <body>
        <div class="header">
        <h3 class="inline">DASHBOARD</h3>
        <h2 class="inline">Welcome {{ user.first_name}}!</h2>
        <a href="{% url 'exam:new_item' %}" class="inline">Add Item</a>
        <a href="{% url 'exam:logout' %}" class="inline">Logout</a>
        </div>
        <p>Your wishlist:</p>
        <table>
            <thead>
                <tr>
                  <th>Item</th>
                  <th>Added By</th>
                  <th>Date Added</th>
                  <th>Actions</th>
                </tr>
            </thead>
            <tbody>
            {% for item in user_items %}
             <!-- <p> {{item.user.all}}<p> {{ item.user.0 }}
                 {% for user in item.user.all %}
                 <p>{{ user.id }}</p>
                 {% endfor %} -->
                <tr>
                  <td><a href="{% url 'exam:item' id=item.id %}">{{ item.name }}</a></td>
                  <td>{{ item.added_by_name }}</td>
                  <td>{{ item.created_at }}</td>
                  {% if request.session.id == item.added_by_id %}
                  <td><a href="{% url 'exam:delete' id=item.id %}">Delete</a></td>
                  {% else %}
                   <td><a href="{% url 'exam:remove' id=item.id %}">Remove from my wish list</a></td>
                  {% endif %}
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <p>Other User's wishlist:</p>
        <table>
            <thead>
                <tr>
                  <th>Item</th>
                  <th>Added By</th>
                  <th>Date Added</th>
                  <th>Actions</th>
                </tr>
            </thead>
            <tbody>
            {% for item in other_items %}
                <tr>
                  <td><a href="{% url 'exam:item' id=item.id %}">{{ item.name }}</a></td>
                  <td>{{ item.added_by_name}}</td>
                  <td>{{ item.created_at }}</td>
                  <td><a href="{% url 'exam:add' id=item.id %}">Add to my wishlist</a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </body>
</html>

apps/exam/templates/exam/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Home</title>
    </head>
    <body>
        <h2>Welcome {{ user.first_name}}!</h2>
        <h3>Do we have a homepage??</h3>

        <p>{{ request.session.id }} {{ user.username }}</p>
    </body>
</html>

apps/exam/templates/exam/item.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        {% load staticfiles %}
        <link rel="stylesheet" href="{% static 'exam/css/style.css' %}">
        <title>Item</title>
    </head>
    <body>
        <div class="header">
            <h3 class="inline">Item</h3>
            <a href="{% url 'exam:dashboard' %}" class="inline">Home</a>
            <a href="{% url 'exam:logout' %}" class="inline">Logout</a>
        </div>
        <h4>{{ item.name }}</h4>
        <p>Users who added this product to their wish list:</p>
        {% for user in users %}
            <p>{{ user.first_name }}</p>
        {% endfor %}
    </body>
</html>