apps/login/urls.py
from django.conf.urls import url, include
from . import views


urlpatterns = [
    url(r'^$', views.index, name = "index"),
    url(r'^success$', views.success, name="success"),
    url(r'^register$', views.register, name="register"),
    url(r'^login$', views.login, name="login"),
    url(r'^logout$', views.logout, name="logout"),
]

beltExam/urls.py
from django.conf.urls import url, include
# from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.login.urls', namespace = 'login')),
    url(r'^exam/', include('apps.exam.urls', namespace = 'exam')),
]

apps/login/models.py
from __future__ import unicode_literals

from django.db import models
import bcrypt
import re

# Create your models here.

class validate(models.Manager):
    def validate(self, postData):
        errors = []
        response = {}
        valid_email = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
        #see if email is in server, return arror if it is
        if self.filter(email = postData['email']):
            errors.append('**Email already in use**')
        if not len(postData['first_name']) >= 3 or not len(postData['last_name']) >= 3:
            errors.append('**Names must be at least 3 characters**')
        if not len(postData['username']) >= 3:
            errors.append('**Username must be at least 3 characters**')
        if not valid_email.match(postData['email']):
            errors.append('**Please enter a valid email address**')
        if not len(postData['password']) >= 8:
            errors.append('**Password must be at least 8 characters**')
        if not postData['password'] == postData['password_confirmation']:
            errors.append('**Passwords didn\'t match**')
        if errors:
            response['status'] = False
            response['errors'] = errors
        else:
            response['status'] = True
            password = postData['password']
            hashed = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt())
            self.create(first_name = postData['first_name'], last_name = postData['last_name'], email = postData['email'], password = hashed, username = postData['username'], created_at = postData['date'])
        return response

    def login(self, postData):
        errors = []
        response = {}
        user = User.objects.filter(email = postData['email'])
        if not user:
            errors.append('**Email not found. Email is case sensitive. **')
            response['status'] = False
            response['errors'] = errors
            return response
        hashed = user[0].password
        check_password = bcrypt.hashpw(postData['password'].encode('utf-8'), hashed.encode('utf-8'))
        if not hashed == check_password:
            errors.append('**Incorrect password**')
            response['status'] = False
            response['errors'] = errors
        else:
            response['status'] = True
        return response

class User(models.Model):
    first_name = models.CharField(max_length = 255)
    last_name = models.CharField(max_length = 255)
    username = models.CharField(max_length=255, default = "User")
    email = models.CharField(max_length = 255)
    password = models.CharField(max_length = 255)
    created_at = models.DateTimeField(auto_now_add = True)
    apdated_at = models.DateTimeField(auto_now = True)
    objects = validate()

apps/login/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib import messages
from .models import User

# Create your views here.
def index(request):
    return render(request, 'login/index.html')

def register(request):
     response = User.objects.validate(request.POST)
     if not response['status']:
        request.session['first_name'] = request.POST['first_name']
        request.session['last_name'] = request.POST['last_name']
        request.session['email'] = request.POST['email']
        request.session['username'] = request.POST['username']
        for error in response['errors']:
            messages.error(request, error)
        return redirect ('login:index')
     else:
         user = User.objects.get(email = request.POST['email'])
         request.session['id'] = user.id
         print request.session['id']
     return redirect('exam:dashboard')
     #EVERYTHING BREAKS, MAKE SURE THE QUERIES USE A UNIWUE THINg

    #     response = Author.objects.add_author(request.POST)
    # if not response['status']:
    #     for error in response['errors']:
    #         messages.error(request, error)
    # # Author.objects.create(name = request.POST['name'])
    # return redirect('/')

def login(request):
    response = User.objects.login(request.POST)
    if not response['status']:
        for error in response['errors']:
            messages.error(request,error)
        return redirect('login:index')
    else:
        user = User.objects.get(email = request.POST['email'])
        request.session['id'] = user.id
        return redirect('exam:dashboard')

def logout(request):
    request.session.clear()
    return redirect ('login:index')

def success(request):
    if request.session['id']:
        context ={
            'users': User.objects.get(id = request.session['id'])
        }
    return render(request, 'login/success.html', context)

apps/login/templates/login/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        {% load staticfiles %}
        <link rel="stylesheet" href="{% static 'exam\css\style.css' %}">
        <title>Login and Registration</title>
    </head>
    <body>
        <div id="wrapper">
            <div class="header">
                <h3 class="inline">Register here!</h3>
            </div>
            {% if messages %}
                {% for message in messages %}
                    <p class="red">{{ message }}</p>
                {% endfor %}
            {% endif %}

            <form action="{%  url 'login:register' %}" method="post">
                {% csrf_token %}
                <label for="" class="left"> First name (at least 3 characters): </label><input type="text" name="first_name" class="right" value="{{request.session.first_name}}">
                <br>
                <label for="" class="left"> Last name (at least 3 characters): </label><input type="text" name="last_name" class="right" value="{{request.session.last_name}}">
                <br>
                <label for="" class="left"> Username (at least 3 characters): </label><input type="text" name="username" class="right" value="{{request.session.username}}">
                <br>
                <label for="" class="left">Email: </label><input type="text" name="email" class="right" value="{{request.session.email}}">
                <br>
                <label for="" class="left">Password (at least 8 characters): </label><input type="password" name="password" class="right">
                <br>
                <label for="" class="left"> Confirm password: </label><input type="password" name="password_confirmation" class="right">
                <br>
                <label for="" class="left"> Date hired???????: </label><input type="datetime-local" name="date" class="right" value="{{placement.date|date:"Y-m-d" }}">
                <input type="submit">
            </form>
            <div class="header">
                <h3>Already have an account? Login here!</h3>
            </div>
            <form action="{% url 'login:login' %}" method="post">
                {% csrf_token %}
                <label for="" class="left">Email: </label><input type="text" name="email" class="right">
                <label for="" class="left"> Password: </label><input type="password" name="password" class="right">
                <input type="submit">
            </form>
        </div>
    </body>
</html>

apps/login/templates/login/success.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        {% load staticfiles %}
        <link rel="stylesheet" href="{% static 'login\css\style.css' %}">
        <title>Success!</title>
    </head>
    <body>
        <div id="wrapper">
            <!-- Get access to variables here!! -->
            <h4>Welcome {{ users.first_name}}!</h4>
            <p>You have logged in in successfully!</p>
            <!-- shoudl I make this a fancy variable that says registered or loggedin? -->
            <form action="/logout">
                <input type="submit" value="Logout">
            </form>

                <p>{{ user.first_name }}</p>
                <p>{{ user.last_name }}</p>
                <p>{{ user.email }}</p>
                <p>{{ user.password }}</p>
        
        </div>
    </body>
</html>